main/urls.py
from django.urls import path, include, register_converter
from django.conf.urls.static import static
from main import views
from webapp import settings


urlpatterns = [
    path('', views.head, name='home'),
    path('about/', views.about, name='about'),
    path('model/', views.MakeCalculations.as_view(), name='model'),
    path('model/result', views.result, name='result'),
    path('download/result/', views.download_pdf, name='download_pdf'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.UsersLogin.as_view(), name='login'),
    path('logout/', views.UsersLogout.as_view(), name='logout'),
    path('register/', views.UsersRegister.as_view(), name='register'),
    path('profile/', views.UsersProfile.as_view(), name='profile'),
    path('password-change', views.UsersPasswordChange.as_view(), name='password-change'),
    path('password-change/done/', views.UsersPasswordChangeDone.as_view(), name='password-change-done')
]

webapp/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users")),
]

handler404 = page_not_found

templates/auth_reg.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <link type="text/css" href="{% static 'users/css/login_style.css' %}" rel="stylesheet" />
  </head>

  <a href="{% url 'users:login' %}"> <img src="{% static 'users/images/login_logo.png' %}" alt="Logo" class="logo"> </a>
  <h1>{{title}}</h1>

{% block func %}
{% endblock %}
</html>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>{{title}}</title>
	<link type="text/css" href="{% static 'main/css/styles.css' %}" rel="stylesheet" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="shortcut icon" href="{% static 'main/images/logo.png' %}" type="image/x-icon"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block styles %}{% endblock %}
</head>
<body>
<table class="table-page" border=0 cellpadding="0" cellspacing="0">
<tr><td valign=top>
{% block mainmenu %}
		<div class="header">
			<ul id="mainmenu" class="mainmenu">
			<li class="logo"><a href="{% url 'home' %}"><div class="logo"></div></a></li>
{% for m in menu %}
				<li class="first"> <a href="{% url m.url_name %}">{{m.title}}</a></li>
{% endfor %}

{% if user.is_authenticated %}
<li class="last">
	<a href="{% url 'users:profile' %}">{{user.username}} </a>
{% endif%}
			</ul>
			<div class="clear"></div>
		</div>
{% endblock mainmenu %}


<table class="table-content" border=0 cellpadding="0" cellspacing="0">
<tr>
<!-- Sidebar слева -->
	<td valign="top" class="left-chapters">
	<ul id="leftchapters">
		<li class="share">
		<p>Links</p>
		<p></p>
		<a class="share-github" href="https://github.com/Vladislav-Baranov/" target="_blank" rel="nofollow"></a>
		</li>
	</ul>
</td>
<!-- Конец Sidebar'а -->
<td valign="top" class="content">
	<!-- Хлебные крошки -->
	{% block breadcrumbs %}
	{% endblock %}

<!-- Блок контента -->
	<div class="content-text">
</ul>
{% block content %}
{% endblock %}

    </ul>
</nav>
	</div>
<!-- Конец блока контента -->

</td></tr></table>
</td></tr>
</body>
</html>